Repository GillesMyny1/SurveyMonkey, pull requests merged in 2023-03, with the labels that each got.

#13 Merge QnA & Answer Branch into Master
  pom.xml
  src/main/java/com/group11/surveymonkey/ChoiceAnswer.java
  src/main/java/com/group11/surveymonkey/ChoiceAnswerController.java
  src/main/java/com/group11/surveymonkey/ChoiceAnswerRepository.java
  src/main/java/com/group11/surveymonkey/ChoiceAnswerService.java
  src/main/java/com/group11/surveymonkey/ChoiceAnswerServiceImpl.java
  src/main/java/com/group11/surveymonkey/ChoiceQnA.java
  src/main/java/com/group11/surveymonkey/ChoiceQnAController.java
  src/main/java/com/group11/surveymonkey/ChoiceQnARepository.java
  src/main/java/com/group11/surveymonkey/ChoiceQnAService.java
  src/main/java/com/group11/surveymonkey/ChoiceQnAServiceImpl.java
  src/main/java/com/group11/surveymonkey/RangeAnswer.java
  src/main/java/com/group11/surveymonkey/RangeAnswerController.java
  src/main/java/com/group11/surveymonkey/RangeAnswerRepository.java
  src/main/java/com/group11/surveymonkey/RangeAnswerService.java
  src/main/java/com/group11/surveymonkey/RangeAnswerServiceImpl.java
  src/main/java/com/group11/surveymonkey/RangeQnA.java
  src/main/java/com/group11/surveymonkey/RangeQnAController.java
  src/main/java/com/group11/surveymonkey/RangeQnARepository.java
  src/main/java/com/group11/surveymonkey/RangeQnAService.java
  src/main/java/com/group11/surveymonkey/RangeQnAServiceImpl.java
  src/main/java/com/group11/surveymonkey/SurveyMonkeyApplication.java
  src/main/java/com/group11/surveymonkey/TextAnswer.java
  src/main/java/com/group11/surveymonkey/TextAnswerController.java
  src/main/java/com/group11/surveymonkey/TextAnswerRepository.java
  src/main/java/com/group11/surveymonkey/TextAnswerService.java
  src/main/java/com/group11/surveymonkey/TextAnswerServiceImpl.java
  src/main/java/com/group11/surveymonkey/TextQnA.java
  src/main/java/com/group11/surveymonkey/TextQnAController.java
  src/main/java/com/group11/surveymonkey/TextQnARepository.java
  src/main/java/com/group11/surveymonkey/TextQnAService.java
  src/main/java/com/group11/surveymonkey/TextQnAServiceImpl.java
Labels: help wanted

#14 Survey classes
  pom.xml
  src/main/java/com/group11/surveymonkey/Survey.java
  src/main/java/com/group11/surveymonkey/SurveyController.java
  src/main/java/com/group11/surveymonkey/SurveyRepository.java
  src/main/java/com/group11/surveymonkey/SurveyService.java
  src/main/java/com/group11/surveymonkey/SurveyServiceImpl.java
Labels: help wanted

#27 Merge database_incorporation to master: Added database incorporation and new question types in the App
  src/main/java/com/group11/surveymonkey/SurveyMonkeyApplication.java
  src/main/resources/application.properties
Labels: enhancement

#32 Range Question and Answer Feature
  src/main/java/com/group11/surveymonkey/SurveyMonkeyApplication.java
  src/main/java/com/group11/surveymonkey/SurveyWebController.java
  src/main/java/com/group11/surveymonkey/entity/ChoiceAnswer.java
  src/main/java/com/group11/surveymonkey/entity/RangeAnswer.java
  src/main/java/com/group11/surveymonkey/entity/RangeQnA.java
  src/main/java/com/group11/surveymonkey/entity/TextAnswer.java
  src/main/java/com/group11/surveymonkey/entity/TextQnA.java
  src/main/resources/public/js/js_scripts.js
  src/main/resources/templates/questionViewer.html
  src/main/resources/templates/rangeAnswerCreate.html
  src/main/resources/templates/rangeAnswerViewer.html
  src/main/resources/templates/rangeQnACreate.html
  src/test/java/com/group11/surveymonkey/SurveyMonkeyApplicationTests.java
  src/test/java/com/group11/surveymonkey/entity/RangeAnswerTest.java
  src/test/java/com/group11/surveymonkey/entity/RangeQnATest.java
Labels: help wanted

#34 Added Edit Survey Info feature
  src/main/java/com/group11/surveymonkey/SurveyWebController.java
  src/main/java/com/group11/surveymonkey/controller/SurveyController.java
  src/main/java/com/group11/surveymonkey/service/SurveyService.java
  src/main/java/com/group11/surveymonkey/serviceimpl/SurveyServiceImpl.java
  src/main/java/com/group11/surveymonkey/serviceimpl/TextAnswerServiceImpl.java
  src/main/resources/templates/editSurvey.html
  src/main/resources/templates/questionViewer.html
  src/main/resources/templates/surveyDisplay.html
Labels: help wanted

#46 Add TextQnA and TextAnswer unit test cases
  src/test/java/com/group11/surveymonkey/entity/TextAnswerTest.java
  src/test/java/com/group11/surveymonkey/entity/TextQnATest.java
Labels: documentation

#54 Added Closing Survey Feature, User Entity Feature, and Perform Authorization Checks Feature
  src/main/java/com/group11/surveymonkey/SurveyMonkeyApplication.java
  src/main/java/com/group11/surveymonkey/SurveyWebController.java
  src/main/java/com/group11/surveymonkey/controller/UserController.java
  src/main/java/com/group11/surveymonkey/entity/Survey.java
  src/main/java/com/group11/surveymonkey/entity/User.java
  src/main/java/com/group11/surveymonkey/repository/UserRepository.java
  src/main/java/com/group11/surveymonkey/service/UserService.java
  src/main/java/com/group11/surveymonkey/serviceimpl/UserServiceImpl.java
  src/main/resources/templates/login.html
  src/main/resources/templates/questionViewer.html
  src/main/resources/templates/resultViewer.html
  src/main/resources/templates/surveyClose.html
  src/main/resources/templates/surveyDisplay.html
  src/test/java/com/group11/surveymonkey/SurveyMonkeyApplicationTests.java
  src/test/java/com/group11/surveymonkey/entity/UserTest.java
Labels: help wanted

#55 Added Unit Tests for Survey Entity
  src/test/java/com/group11/surveymonkey/entity/SurveyTest.java
Labels: enhancement

#56 Added Histogram Viewer for Range Questions for a Closed Survey
  src/main/java/com/group11/surveymonkey/SurveyWebController.java
  src/main/resources/templates/resultViewer.html
Labels: enhancement
